### PR TITLE
Fixes #16 - Mask the unlocking of a non-existant account

### LINKED ISSUE #16: /account/:id/unlock of a non existent account differs in behavior from fxa-auth-db-mysql
The MySQL driver succeeds whereas the memory driver fails with a 404 (not found).

Cross filed as https://github.com/mozilla/fxa-auth-db-mysql/issues/11

### PR DESCRIPTION
**Pull request by chilts**

### CODE REVIEW

File: db.js [hunk 1]
```diff
@@ -461,6 +461,10 @@ module.exports = function (log, error) {
           account.lockedAt = null
           delete accountUnlockCodes[uid]
           return {}
+        },
+        function(err) {
+          // the only error from this.account(uid) could be a 404 Not Found - mask this
```
Comment (rfk) [inline db.js]: It may be worth commenting on *why* we're masking it, just for future readers.  e.g. "it's harmless and simpler to just ignore it than force error handling downstream".

**Comment by rfk** [comment]
Comment aside, r+
